spring:
  profiles:
    active: prod
    group:
      local:
        - common
      prod:
        - common
      test:
        - common
---
spring:
  config:
    activate:
      on-profile: common

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger-ui
    operations-sorter: alpha
    tags-sorter: alpha

firebase:
  config:
    path: classpath:/firebase/runit-firebase-key.json

schedule:
  week-start:
    cron: 0 0 0 ? * MON

logging:
  level:
    root: INFO
    com.ssafy.runit: DEBUG