server:
  port: ${RUNIT_PORT}

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger-ui
    operations-sorter: alpha
    tags-sorter: alpha

spring:
  application:
    name: runIt

  output:
    ansi:
      enabled: always

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_ID}
    password: ${DATABASE_ID}
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  jpa:
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    hibernate:
      ddl-auto: update
    #show-sql: true

logging:
  level:
    root: INFO
    com.ssafy.runit: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 7200000 # 2h
  refresh-token-expiration: 604800000 # 7d

firebase:
  config:
    path: classpath:/firebase/runit-firebase-key.json

schedule:
  week-start:
    cron: 0 0 0 ? * MON